model:
  base_learning_rate: 7.5e-05   # set to target_lr by starting main.py with '--scale_lr False'
  target: ldm.models.diffusion.ddpm.LatentInpaintDiffusion
  params:
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    loss_type: l1
    first_stage_key: "image"
    cond_stage_key: "caption"
    image_size: 64
    channels: 4
    cond_stage_trainable: False
    conditioning_key: hybrid   # important
    monitor: 'val/loss_simple_ema'
    scale_factor: 0.18215
    finetune_keys: null
    ckpt_path: /home/juncfang/code/stable-diffusion/models/ldm/stable-diffusion-v1/sd-v1-5-inpainting.ckpt

    scheduler_config: # 10000 warmup steps
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [ 2500 ] # NOTE for resuming. use 10000 if starting from scratch
        cycle_lengths: [10000000000000]
        f_start: [1.e-6]
        f_max: [1.]
        f_min: [ 1.]

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 32
        in_channels: 9  # 4 data + 4 downscaled image + 1 mask
        out_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_heads: 8
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 768
        use_checkpoint: True
        legacy: False

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: "val/rec_loss"
        ddconfig:
          double_z: True
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult: 
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: [ ]
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config: 
      target: ldm.modules.encoders.modules.FrozenCLIPEmbedder

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 2
    num_workers: 5
    wrap: false
    train:
      target: personal_workspace.inpainting_dataset.InpaintingTrain
      params:
        data_root: /opt/disk1/juncfang/data/Inpainting_data/230613_id_photo_6_11_inpainting
        mask_type: random
        size: 512
        interpolation: bicubic
    validation:
      target: personal_workspace.inpainting_dataset.InpaintingValidation
      params:
        data_root: /opt/disk1/juncfang/data/Inpainting_data/230613_id_photo_6_11_inpainting
        mask_type: hybrid
        size: 512
        interpolation: bicubic

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 5000
        max_images: 8
        increase_log_steps: False
        disabled: True


  trainer:
    benchmark: True
    gpus: 0,1,2,3
    # gpus: 0,
    max_epochs: 20
    check_val_every_n_epoch: 1